language: node_js
node_js:
  - 12
  - 11
  - 10
  - 8
os:
  - linux
  - osx
  - windows
addons:
  chrome: stable
matrix:
  allow_failures:
    - os: windows
before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install googlechrome -y; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then export "PATH='/C:/Program Files (x86)/Google/Chrome/Application':$PATH"; fi
script:
  - npm run test_headless
  - npm run lint
  - npm run build
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm install codecov -g; fi
  - if [ "$TRAVIS_OS_NAME" != "windows" ]; then codecov; fi