name: 'www'
on: ['push', 'pull_request']
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['12', '14']
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm update
      - run: npm install puppeteer --save-dev
      # - run: npm run test_headless
      - run: npm run lint
      - run: npm install -g codecov
      - run: codecov
      - run: npm run build
        env:
          CI: true